"""Lorekeeper memory provider — Hermes plugin.

Talks to the Lorekeeper Node service (localhost HTTP) which owns the
LanceDB store, embedder, and entity graph. This module is a thin
MemoryProvider implementation: config, tool schemas, prefetch, dispatch.

Config lives in ``$HERMES_HOME/lorekeeper.json`` (written by
``hermes memory setup``); the bearer token is read from
``$HERMES_HOME/lorekeeper/token`` (auto-generated by the service) or the
``LOREKEEPER_TOKEN`` env var.
"""

from __future__ import annotations

import json
import logging
import os
import threading
from contextlib import suppress
from pathlib import Path
from typing import Any, Dict, List, Optional

from agent.memory_provider import MemoryProvider
from agent.secret_scope import get_secret
from tools.registry import tool_error

from ._client import LorekeeperClient, LorekeeperError

logger = logging.getLogger(__name__)

_DEFAULT_HOST = "http://127.0.0.1:18777"
_PREFETCH_WAIT_SECS = 3


def _read_config(hermes_home: Path) -> dict:
    """Best-effort read of lorekeeper.json; missing/corrupt -> {}."""
    path = hermes_home / "lorekeeper.json"
    if path.exists():
        with suppress(Exception):
            return json.loads(path.read_text(encoding="utf-8"))
    return {}


def _read_token(hermes_home: Path) -> str:
    """Token precedence: env > service-written token file."""
    env = os.environ.get("LOREKEEPER_TOKEN") or get_secret("LOREKEEPER_TOKEN", "")
    if env:
        return env
    token_file = hermes_home / "lorekeeper" / "token"
    with suppress(Exception):
        return token_file.read_text(encoding="utf-8").strip()
    return ""


def _schema(name: str, description: str, properties: dict, required: list) -> dict:
    props = {k: {"type": t, "description": d} for k, (t, d) in properties.items()}
    return {"name": name, "description": description, "parameters": {"type": "object", "properties": props, "required": required}}


TOOL_SCHEMAS = [
    _schema(
        "lorekeeper_search",
        "Search long-term memory (LanceDB vector + BM25 hybrid). Use before answering anything that may depend on what you know about the user — preferences, facts, history, projects, past decisions. For multi-part questions, search several times with different wording.",
        {"query": ("string", "What to search for."), "limit": ("integer", "Max results (default: 5, max: 20).")},
        ["query"],
    ),
    _schema(
        "lorekeeper_remember",
        "Store a durable fact about the user, verbatim. Call this the moment the user states a lasting preference, correction, decision, or personal detail worth recalling on future turns. Skip transient chit-chat.",
        {"content": ("string", "The fact to store."), "category": ("string", "Optional category (e.g. preference, fact, decision)."), "importance": ("number", "Importance 0-1 (default 0.5).")},
        ["content"],
    ),
    _schema(
        "lorekeeper_delete",
        "Delete a memory by its ID (take the ID from a lorekeeper_search result). Use when a stored fact is obsolete or the user asks you to forget it.",
        {"memory_id": ("string", "Memory ID to delete."), "force": ("boolean", "Hard-delete instead of soft-delete (default false).")},
        ["memory_id"],
    ),
    _schema(
        "lorekeeper_stats",
        "Show Lorekeeper memory store status: total memories, per-scope counts, index health, embedder.",
        {},
        [],
    ),
]

_PROMPT_BODY = (
    "You have persistent long-term memory via Lorekeeper (LanceDB vector store). "
    "Call lorekeeper_search before answering anything that could depend on prior context — "
    "do not rely on the chat window alone. Use lorekeeper_remember to store durable facts, "
    "lorekeeper_delete to remove obsolete ones."
)


class LorekeeperMemoryProvider(MemoryProvider):
    """Lorekeeper — local LanceDB long-term memory via the Node service."""

    def __init__(self):
        self._client = self._host = self._token = None
        self._config = {}
        self._channel = "cli"
        self._prefetch_query = self._prefetch_result = ""
        self._prefetch_done = False
        self._prefetch_thread = None
        self._prefetch_lock = threading.Lock()

    @property
    def name(self) -> str:
        return "lorekeeper"

    # -- config --------------------------------------------------------------

    def is_available(self) -> bool:
        """Configured? (config file, token file, or env). No network here."""
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        return bool(_read_config(home) or _read_token(home) or os.environ.get("LOREKEEPER_HOST"))

    def get_config_schema(self) -> List[Dict[str, Any]]:
        return [
            {"key": "host", "description": "Lorekeeper service URL", "default": _DEFAULT_HOST, "required": False, "env_var": "LOREKEEPER_HOST"},
            {"key": "token", "description": "Bearer token (blank: read from ~/.hermes/lorekeeper/token)", "secret": True, "required": False, "env_var": "LOREKEEPER_TOKEN"},
        ]

    def save_config(self, values: Dict[str, Any], hermes_home: str) -> None:
        from utils import atomic_json_write

        path = Path(hermes_home) / "lorekeeper.json"
        atomic_json_write(path, {**_read_config(Path(hermes_home)), **values}, mode=0o600)

    # -- lifecycle -----------------------------------------------------------

    def initialize(self, session_id: str, **kwargs) -> None:
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        cfg = _read_config(home)
        self._config = cfg
        self._host = (cfg.get("host") or os.environ.get("LOREKEEPER_HOST") or _DEFAULT_HOST).rstrip("/")
        self._token = (cfg.get("token") or _read_token(home)) or ""
        self._channel = kwargs.get("platform") or "cli"
        if self._host and self._token:
            self._client = LorekeeperClient(self._host, self._token)
            # Best-effort health ping; failures surface via tools, not startup.
            with suppress(Exception):
                self._client.health()

    def shutdown(self) -> None:
        with suppress(Exception):
            if self._client:
                self._client.close()
                self._client = None

    def system_prompt_block(self) -> str:
        mode = "active" if self._client else "unavailable (service not reachable)"
        return f"# Lorekeeper Memory\nLong-term memory via Lorekeeper (LanceDB). Status: {mode}.\n{_PROMPT_BODY}"

    # -- recall --------------------------------------------------------------

    def on_turn_start(self, turn_number: int, message: str, **kwargs) -> None:
        self._start_prefetch(message)

    def _start_prefetch(self, query: str) -> None:
        client = self._client
        if not query or client is None:
            return

        def _run():
            try:
                results = client.search(query, limit=5)
            except Exception as e:
                logger.debug("Lorekeeper prefetch failed: %s", e)
                return
            lines = [f"- {r.get('text', '')}" for r in results.get("results", []) if r.get("text")]
            body = "## Lorekeeper Memory\n" + "\n".join(lines) if lines else ""
            with self._prefetch_lock:
                if self._prefetch_query == query:
                    self._prefetch_result, self._prefetch_done = body, True

        with self._prefetch_lock:
            if self._prefetch_query == query and (self._prefetch_done or (self._prefetch_thread and self._prefetch_thread.is_alive())):
                return
            self._prefetch_query, self._prefetch_result, self._prefetch_done = query, "", False
            self._prefetch_thread = t = threading.Thread(target=_run, daemon=True, name="lorekeeper-prefetch")
        t.start()

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        with self._prefetch_lock:
            if self._prefetch_query != query or not self._prefetch_done:
                cached = None
            else:
                cached, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
            thread = self._prefetch_thread if self._prefetch_query == query else None
        if cached is not None:
            return cached
        self._start_prefetch(query)
        if thread:
            thread.join(timeout=_PREFETCH_WAIT_SECS)
        with self._prefetch_lock:
            if self._prefetch_query == query and self._prefetch_done:
                result, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
                return result
        return ""

    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str = "", messages: Optional[List[Dict[str, Any]]] = None) -> None:
        # Auto-capture endpoint not built yet (Phase 4 in PLAN.md); no-op for now.
        pass

    # -- tools ---------------------------------------------------------------

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        return list(TOOL_SCHEMAS)

    def _tool_search(self, args: dict) -> str:
        limit = max(1, min(int(args.get("limit", 5)), 20))
        results = self._client.search(args["query"], limit=limit)
        items = results.get("results", [])
        if not items:
            return json.dumps({"result": "No relevant memories found."})
        return json.dumps({"results": items, "count": len(items)})

    def _tool_remember(self, args: dict) -> str:
        result = self._client.remember(args["content"], category=args.get("category"), importance=args.get("importance"))
        return json.dumps({"result": "Memory stored.", "id": result.get("id")})

    def _tool_delete(self, args: dict) -> str:
        result = self._client.delete(args["memory_id"], force=bool(args.get("force", False)))
        return json.dumps({"result": "Memory deleted.", "id": args["memory_id"]})

    def _tool_stats(self, args: dict) -> str:
        return json.dumps(self._client.stats())

    _TOOL_HANDLERS = {
        "lorekeeper_search": (("query",), "Search failed", _tool_search),
        "lorekeeper_remember": (("content",), "Failed to store", _tool_remember),
        "lorekeeper_delete": (("memory_id",), "Delete failed", _tool_delete),
        "lorekeeper_stats": ((), "Stats failed", _tool_stats),
    }

    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs) -> str:
        if self._client is None:
            return json.dumps({"error": "Lorekeeper service not initialized. Is the service running? (see Lorekeeper README)"})
        if tool_name not in self._TOOL_HANDLERS:
            return tool_error(f"Unknown tool: {tool_name}")
        required, label, body = self._TOOL_HANDLERS[tool_name]
        if missing := next((k for k in required if not args.get(k, "")), None):
            return tool_error(f"Missing required parameter: {missing}")
        try:
            return body(self, args)
        except LorekeeperError as e:
            return tool_error(f"{label}: {e}")
        except Exception as e:
            return tool_error(f"{label}: {e}")


def register(ctx) -> None:
    """Register Lorekeeper as a memory provider plugin."""
    ctx.register_memory_provider(LorekeeperMemoryProvider())