"""Lorekeeper memory provider — Hermes plugin.

Talks to the Lorekeeper Node service (localhost HTTP) which owns the
LanceDB store, embedder, and entity graph. This module is a thin
MemoryProvider implementation: config, tool schemas, prefetch, dispatch.

Config lives in ``$HERMES_HOME/lorekeeper.json`` (written by
``hermes memory setup``); the bearer token is read from
``$HERMES_HOME/lorekeeper/token`` (auto-generated by the service) or the
``LOREKEEPER_TOKEN`` env var.
"""

from __future__ import annotations

import json
import logging
import os
import threading
from contextlib import suppress
from pathlib import Path
from typing import Any, Dict, List, Optional

from agent.memory_provider import MemoryProvider
from agent.secret_scope import get_secret
from tools.registry import tool_error

from ._client import LorekeeperClient, LorekeeperError

logger = logging.getLogger(__name__)

_DEFAULT_HOST = "http://127.0.0.1:18777"
_PREFETCH_WAIT_SECS = 3
# Capture buffer bounds (mirror the fork's CAPTURE_BUFFER_BOUNDS): keep the
# newest tail, cap total chars per session so a failing service can't grow
# memory without bound.
_CAPTURE_MAX_CHARS = 60000


def _read_config(hermes_home: Path) -> dict:
    """Best-effort read of lorekeeper.json; missing/corrupt -> {}."""
    path = hermes_home / "lorekeeper.json"
    if path.exists():
        with suppress(Exception):
            return json.loads(path.read_text(encoding="utf-8"))
    return {}


def _read_token(hermes_home: Path) -> str:
    """Token precedence: env > service-written token file."""
    env = os.environ.get("LOREKEEPER_TOKEN") or get_secret("LOREKEEPER_TOKEN", "")
    if env:
        return env
    token_file = hermes_home / "lorekeeper" / "token"
    with suppress(Exception):
        return token_file.read_text(encoding="utf-8").strip()
    return ""


_PROMPT_BODY = (
    "You have persistent long-term memory via Lorekeeper (LanceDB vector store). "
    "Call lorekeeper_search before answering anything that could depend on prior context — "
    "do not rely on the chat window alone. Use lorekeeper_remember to store durable facts, "
    "lorekeeper_delete to remove obsolete ones."
)


class LorekeeperMemoryProvider(MemoryProvider):
    """Lorekeeper — local LanceDB long-term memory via the Node service."""

    def __init__(self):
        self._client = self._host = self._token = None
        self._config = {}
        self._channel = "cli"
        self._prefetch_query = self._prefetch_result = ""
        self._prefetch_done = False
        self._prefetch_thread = None
        self._prefetch_lock = threading.Lock()
        # Capture: per-session text buffers + in-flight guards (thread-safe).
        self._capture_buffers: Dict[str, str] = {}
        self._capture_flushing: set = set()
        self._capture_lock = threading.Lock()
        self._current_session = ""

    @property
    def name(self) -> str:
        return "lorekeeper"

    # -- config --------------------------------------------------------------

    def is_available(self) -> bool:
        """Configured? (config file, token file, or env). No network here."""
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        return bool(_read_config(home) or _read_token(home) or os.environ.get("LOREKEEPER_HOST"))

    def get_config_schema(self) -> List[Dict[str, Any]]:
        return [
            {"key": "host", "description": "Lorekeeper service URL", "default": _DEFAULT_HOST, "required": False, "env_var": "LOREKEEPER_HOST"},
            {"key": "token", "description": "Bearer token (blank: read from ~/.hermes/lorekeeper/token)", "secret": True, "required": False, "env_var": "LOREKEEPER_TOKEN"},
        ]

    def save_config(self, values: Dict[str, Any], hermes_home: str) -> None:
        from utils import atomic_json_write

        path = Path(hermes_home) / "lorekeeper.json"
        atomic_json_write(path, {**_read_config(Path(hermes_home)), **values}, mode=0o600)

    # -- lifecycle -----------------------------------------------------------

    def initialize(self, session_id: str, **kwargs) -> None:
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        cfg = _read_config(home)
        self._config = cfg
        self._host = (cfg.get("host") or os.environ.get("LOREKEEPER_HOST") or _DEFAULT_HOST).rstrip("/")
        self._token = (cfg.get("token") or _read_token(home)) or ""
        self._channel = kwargs.get("platform") or "cli"
        self._current_session = session_id or ""
        if self._host and self._token:
            self._client = LorekeeperClient(self._host, self._token)
            # Best-effort health ping; failures surface via tools, not startup.
            with suppress(Exception):
                self._client.health()

    def shutdown(self) -> None:
        with suppress(Exception):
            if self._client:
                self._client.close()
                self._client = None

    def system_prompt_block(self) -> str:
        mode = "active" if self._client else "unavailable (service not reachable)"
        return f"# Lorekeeper Memory\nLong-term memory via Lorekeeper (LanceDB). Status: {mode}.\n{_PROMPT_BODY}"

    # -- recall --------------------------------------------------------------

    def on_turn_start(self, turn_number: int, message: str, **kwargs) -> None:
        self._start_prefetch(message)

    def _start_prefetch(self, query: str) -> None:
        client = self._client
        if not query or client is None:
            return

        def _run():
            try:
                results = client.search(query, limit=5)
            except Exception as e:
                logger.debug("Lorekeeper prefetch failed: %s", e)
                return
            lines = [f"- {r.get('text', '')}" for r in results.get("results", []) if r.get("text")]
            body = "## Lorekeeper Memory\n" + "\n".join(lines) if lines else ""
            with self._prefetch_lock:
                if self._prefetch_query == query:
                    self._prefetch_result, self._prefetch_done = body, True

        with self._prefetch_lock:
            if self._prefetch_query == query and (self._prefetch_done or (self._prefetch_thread and self._prefetch_thread.is_alive())):
                return
            self._prefetch_query, self._prefetch_result, self._prefetch_done = query, "", False
            self._prefetch_thread = t = threading.Thread(target=_run, daemon=True, name="lorekeeper-prefetch")
        t.start()

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        with self._prefetch_lock:
            if self._prefetch_query != query or not self._prefetch_done:
                cached = None
            else:
                cached, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
            thread = self._prefetch_thread if self._prefetch_query == query else None
        if cached is not None:
            return cached
        self._start_prefetch(query)
        if thread:
            thread.join(timeout=_PREFETCH_WAIT_SECS)
        with self._prefetch_lock:
            if self._prefetch_query == query and self._prefetch_done:
                result, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
                return result
        return ""

    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str = "", messages: Optional[List[Dict[str, Any]]] = None) -> None:
        """Buffer the completed turn and flush to /capture (non-blocking).

        Mirrors the fork's capture-on-idle: each turn's text is appended to a
        per-session buffer; once it crosses _CAPTURE_FLUSH_CHARS (or the
        session ends / compresses), the buffer is sent to the service which
        runs heuristics extraction and stores what's memory-worthy.
        """
        if self._client is None:
            return
        text = f"{user_content or ''}\n{assistant_content or ''}".strip()
        if not text:
            return
        sid = session_id or "default"
        with self._capture_lock:
            prev = self._capture_buffers.get(sid, "")
            combined = f"{prev}\n{text}" if prev else text
            # Keep the newest tail (mirror CAPTURE_TAIL_KEEP).
            if len(combined) > _CAPTURE_MAX_CHARS:
                combined = combined[-_CAPTURE_MAX_CHARS:]
            self._capture_buffers[sid] = combined
        # Flush every turn (mirrors the fork's capture-on-session-idle). The
        # service's minCaptureChars gate filters noise; dedup blocks repeats.
        self._flush_capture(sid, synchronous=False)

    def _flush_capture(self, session_id: str, *, synchronous: bool) -> None:
        """Send the session's buffered text to /capture. On failure the buffer
        is retained for the next flush (mirror CAPTURE_BUFFER_AFTER_WRITES)."""
        with self._capture_lock:
            if session_id in self._capture_flushing:
                return
            text = self._capture_buffers.get(session_id, "")
            if not text:
                return
            self._capture_buffers.pop(session_id, None)
            self._capture_flushing.add(session_id)

        def _run():
            try:
                self._client.capture({"sessionID": session_id, "text": text})
            except Exception as e:
                logger.debug("Lorekeeper capture flush failed: %s", e)
                # Retain for next flush.
                with self._capture_lock:
                    prev = self._capture_buffers.get(session_id, "")
                    self._capture_buffers[session_id] = f"{prev}\n{text}" if prev else text
            finally:
                with self._capture_lock:
                    self._capture_flushing.discard(session_id)

        if synchronous:
            _run()
        else:
            threading.Thread(target=_run, daemon=True, name="lorekeeper-capture").start()

    def on_session_end(self, messages: List[Dict[str, Any]]) -> None:
        """Flush any buffered capture at a real session boundary."""
        self._flush_capture(self._current_session, synchronous=False)

    def on_session_switch(
        self, new_session_id: str, *, parent_session_id: str = "", reset: bool = False, rewound: bool = False, **kwargs,
    ) -> None:
        """Rebind capture buffers on session switch; flush on a genuinely new
        conversation so nothing buffered is lost."""
        if reset and self._current_session and self._current_session != new_session_id:
            self._flush_capture(self._current_session, synchronous=False)
        self._current_session = new_session_id

    def on_pre_compress(self, messages: List[Dict[str, Any]]) -> str:
        """Flush before compression so the compressed-away content is captured."""
        if self._current_session:
            self._flush_capture(self._current_session, synchronous=False)
        return ""

    # -- tools ---------------------------------------------------------------

    def _ensure_client(self) -> None:
        """Build the client from config/token without session kwargs.

        MemoryManager.add_provider() calls get_tool_schemas() BEFORE
        initialize() has run (initialize is what normally builds the
        client), so get_tool_schemas() must be able to build it lazily —
        otherwise the provider registers 0 tools, the dispatch routing
        table stays empty, and every lorekeeper_* call falls through to
        the registry as "Unknown tool". initialize() re-reads the same
        config and re-creates the client, so this is safe to call early.
        """
        if self._client is not None:
            return
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        cfg = _read_config(home)
        host = (cfg.get("host") or os.environ.get("LOREKEEPER_HOST") or _DEFAULT_HOST).rstrip("/")
        token = (cfg.get("token") or _read_token(home)) or ""
        if host and token:
            self._client = LorekeeperClient(host, token)

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        """Fetch the full tool surface from the service (34 fork tools)."""
        if self._client is None:
            self._ensure_client()
        if self._client is None:
            return []
        try:
            resp = self._client.tools()
            return resp.get("tools", [])
        except Exception as e:
            logger.debug("Lorekeeper tool schema fetch failed: %s", e)
            return []

    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs) -> str:
        """Generic dispatch: every lorekeeper_* tool runs on the service."""
        if self._client is None:
            return json.dumps({"error": "Lorekeeper service not initialized. Is the service running? (see Lorekeeper README)"})
        try:
            result = self._client.tool(tool_name, args)
            # The service returns {result: <string|object|array>}.
            payload = result.get("result")
            if isinstance(payload, str):
                return payload
            return json.dumps(payload)
        except LorekeeperError as e:
            return tool_error(f"Lorekeeper tool failed: {e}")
        except Exception as e:
            return tool_error(f"Lorekeeper tool failed: {e}")


def register(ctx) -> None:
    """Register Lorekeeper as a memory provider plugin."""
    ctx.register_memory_provider(LorekeeperMemoryProvider())