"""Lorekeeper memory provider — Hermes plugin.

Talks to the Lorekeeper Node service (localhost HTTP) which owns the
LanceDB store, embedder, and entity graph. This module is a thin
MemoryProvider implementation: config, tool schemas, prefetch, dispatch.

Config lives in ``$HERMES_HOME/lorekeeper.json`` (written by
``hermes memory setup``); the bearer token is read from
``$HERMES_HOME/lorekeeper/token`` (auto-generated by the service) or the
``LOREKEEPER_TOKEN`` env var.
"""

from __future__ import annotations

import json
import logging
import os
import re
import threading
from concurrent.futures import Future, ThreadPoolExecutor
from contextlib import suppress
from pathlib import Path
from typing import Any, Dict, List, Optional

from agent.memory_provider import MemoryProvider
from agent.secret_scope import get_secret
from tools.registry import tool_error

from ._client import LorekeeperError, error_from_result
from ._shared import get_client, get_tool_schemas
from ._version import __version__

logger = logging.getLogger(__name__)

_DEFAULT_HOST = "http://127.0.0.1:18777"
_PREFETCH_WAIT_SECS = 3
# Capture buffer bounds (mirror the fork's CAPTURE_BUFFER_BOUNDS): keep the
# newest tail, cap total chars per session so a failing service can't grow
# memory without bound.
_CAPTURE_MAX_CHARS = 60000
# Flush threshold: turns are buffered per session and sent to /capture in
# batches. capture.mode=llm means every flush is an LLM extraction call, so
# flushing per turn costs one LLM round-trip per turn — threshold flushing
# cuts that by ~10x. Override via lorekeeper.json "captureFlushChars".
_CAPTURE_FLUSH_CHARS = 1200
# Cap on assistant text fed to a single turn's buffer: extraction only needs
# the substance, not full code dumps (assistant output can hit 60k chars).
_CAPTURE_TURN_MAX_CHARS = 6000
# Prefetch query shaping: the raw turn text is a poor recall query when long —
# the embedder averages every topic into one diluted vector and BM25 floods.
# Cap the query (user messages front-load intent) and drop embedding poison
# (code blocks, URLs). Override via lorekeeper.json "prefetchQueryChars".
_PREFETCH_QUERY_CHARS_DEFAULT = 400

_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
_URL_RE = re.compile(r"https?://\S+")
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.?!])\s+")


def _shape_prefetch_query(message: str, max_chars: int) -> str:
    """Shape a turn's raw text into a concise recall query.

    Order: strip embedding poison (fenced code blocks, URLs), collapse
    whitespace; if it fits, that's the query. Otherwise prefer question
    sentences (the actual ask), falling back to head truncation at a
    sentence boundary. Idempotent: shaping an already-shaped query returns
    it unchanged (safe to apply in both on_turn_start and prefetch).
    """
    text = message or ""
    if not text.strip():
        return ""
    text = _FENCE_RE.sub(" ", text)
    text = _URL_RE.sub(" ", text)
    text = " ".join(text.split())
    if len(text) <= max_chars:
        return text
    questions = [s for s in _SENTENCE_SPLIT_RE.split(text) if s.endswith("?")]
    picked = " ".join(questions)
    if picked and len(picked) <= max_chars:
        return picked
    head = text[:max_chars]
    cut = max(head.rfind(". "), head.rfind("? "), head.rfind("! "))
    if cut > max_chars // 2:
        return head[:cut + 1]
    space = head.rfind(" ")
    return head[:space] if space > 0 else head


def _read_config(hermes_home: Path) -> dict:
    """Best-effort read of lorekeeper.json; missing/corrupt -> {}."""
    path = hermes_home / "lorekeeper.json"
    if path.exists():
        with suppress(Exception):
            return json.loads(path.read_text(encoding="utf-8"))
    return {}


def _read_token(hermes_home: Path) -> str:
    """Token precedence: env > service-written token file."""
    env = os.environ.get("LOREKEEPER_TOKEN") or get_secret("LOREKEEPER_TOKEN", "")
    if env:
        return env
    token_file = hermes_home / "lorekeeper" / "token"
    with suppress(Exception):
        return token_file.read_text(encoding="utf-8").strip()
    return ""


_PROMPT_BODY = (
    "You have persistent long-term memory via Lorekeeper (LanceDB vector store). "
    "Call lorekeeper_search before answering anything that could depend on prior context — "
    "do not rely on the chat window alone. Use lorekeeper_remember to store durable facts, "
    "lorekeeper_delete to remove obsolete ones."
)


class LorekeeperMemoryProvider(MemoryProvider):
    """Lorekeeper — local LanceDB long-term memory via the Node service."""

    def __init__(self):
        self._client = self._host = self._token = None
        self._config = {}
        self._channel = "cli"
        self._prefetch_query = self._prefetch_result = ""
        self._prefetch_done = False
        self._prefetch_future: Optional[Future] = None
        self._prefetch_lock = threading.Lock()
        # Shared worker pool for the fire-and-forget jobs (prefetch search,
        # capture flush) — replaces a fresh daemon thread per turn.
        self._executor = ThreadPoolExecutor(max_workers=4, thread_name_prefix="lorekeeper")
        # Capture: per-session text buffers + in-flight guards (thread-safe).
        self._capture_buffers: Dict[str, str] = {}
        self._capture_flushing: set = set()
        self._capture_lock = threading.Lock()
        self._current_session = ""

    @property
    def name(self) -> str:
        return "lorekeeper"

    # -- config --------------------------------------------------------------

    def is_available(self) -> bool:
        """Configured? (config file, token file, or env). No network here."""
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        return bool(_read_config(home) or _read_token(home) or os.environ.get("LOREKEEPER_HOST"))

    def get_config_schema(self) -> List[Dict[str, Any]]:
        return [
            {"key": "host", "description": "Lorekeeper service URL", "default": _DEFAULT_HOST, "required": False, "env_var": "LOREKEEPER_HOST"},
            {"key": "token", "description": "Bearer token (blank: read from ~/.hermes/lorekeeper/token)", "secret": True, "required": False, "env_var": "LOREKEEPER_TOKEN"},
        ]

    def save_config(self, values: Dict[str, Any], hermes_home: str) -> None:
        from utils import atomic_json_write

        path = Path(hermes_home) / "lorekeeper.json"
        atomic_json_write(path, {**_read_config(Path(hermes_home)), **values}, mode=0o600)

    # -- lifecycle -----------------------------------------------------------

    def initialize(self, session_id: str, **kwargs) -> None:
        from hermes_constants import get_hermes_home

        home = get_hermes_home()
        cfg = _read_config(home)
        self._config = cfg
        self._host = (cfg.get("host") or os.environ.get("LOREKEEPER_HOST") or _DEFAULT_HOST).rstrip("/")
        self._token = (cfg.get("token") or _read_token(home)) or ""
        self._channel = kwargs.get("platform") or "cli"
        self._current_session = session_id or ""
        if self._host and self._token:
            # Shared singleton (same instance the plugin toolset uses) —
            # one keep-alive connection + one /tools fetch per build.
            self._client = get_client()
            # Best-effort health ping; failures surface via tools, not startup.
            # The ping doubles as the version handshake: provider version +
            # the service's own version, so the log shows which code is live.
            with suppress(Exception):
                service = (self._client.health() or {}).get("version", "unknown")
                logger.info("Lorekeeper provider v%s ready (service v%s at %s)", __version__, service, self._host)

    def shutdown(self) -> None:
        # The client is the shared process-lifetime singleton (the plugin
        # toolset holds it too) — drop the reference, don't close the
        # connection; closing would just force a transparent reconnect.
        with suppress(Exception):
            self._executor.shutdown(wait=False)
        self._client = None

    def system_prompt_block(self) -> str:
        mode = "active" if self._client else "unavailable (service not reachable)"
        return f"# Lorekeeper Memory\nLong-term memory via Lorekeeper (LanceDB). Status: {mode}.\n{_PROMPT_BODY}"

    # -- recall --------------------------------------------------------------

    def _prefetch_query_text(self, message: str) -> str:
        """Shape the turn text for recall (see _shape_prefetch_query). Applied
        identically in on_turn_start and prefetch so both entry points key on
        the same shaped query — shaping is idempotent."""
        if not message or not isinstance(message, str):
            return message if isinstance(message, str) else ""
        try:
            max_chars = int(self._config.get("prefetchQueryChars") or _PREFETCH_QUERY_CHARS_DEFAULT)
        except (TypeError, ValueError):
            max_chars = _PREFETCH_QUERY_CHARS_DEFAULT
        shaped = _shape_prefetch_query(message, max_chars)
        return shaped or message[:max_chars].strip()

    def on_turn_start(self, turn_number: int, message: str, **kwargs) -> None:
        self._start_prefetch(self._prefetch_query_text(message))

    def _start_prefetch(self, query: str) -> Optional[Future]:
        client = self._client
        if not query or client is None:
            return None

        def _run():
            try:
                results = client.search(query, limit=5)
            except Exception as e:
                logger.debug("Lorekeeper prefetch failed: %s", e)
                return
            lines = [f"- {r.get('text', '')}" for r in results.get("results", []) if r.get("text")]
            body = "## Lorekeeper Memory\n" + "\n".join(lines) if lines else ""
            with self._prefetch_lock:
                if self._prefetch_query == query:
                    self._prefetch_result, self._prefetch_done = body, True

        with self._prefetch_lock:
            if self._prefetch_query == query and (self._prefetch_done or (self._prefetch_future and not self._prefetch_future.done())):
                return self._prefetch_future
            self._prefetch_query, self._prefetch_result, self._prefetch_done = query, "", False
            self._prefetch_future = fut = self._executor.submit(_run)
        return fut

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        query = self._prefetch_query_text(query)
        with self._prefetch_lock:
            if self._prefetch_query != query or not self._prefetch_done:
                cached = None
            else:
                cached, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
            fut = self._prefetch_future if self._prefetch_query == query else None
        if cached is not None:
            return cached
        fut = self._start_prefetch(query) or fut
        if fut:
            with suppress(Exception):  # TimeoutError / worker error -> "" below
                fut.result(timeout=_PREFETCH_WAIT_SECS)
        with self._prefetch_lock:
            if self._prefetch_query == query and self._prefetch_done:
                result, self._prefetch_result, self._prefetch_done = self._prefetch_result, "", False
                return result
        return ""

    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str = "", messages: Optional[List[Dict[str, Any]]] = None) -> None:
        """Buffer the completed turn; flush at the threshold (or on session
        end / compress / switch — those call _flush_capture directly).

        Mirrors the fork's capture-on-idle design: turns are batched per
        session so the service runs LLM extraction once per threshold, not
        once per turn. The service's minCaptureChars gate filters noise; dedup
        blocks repeats.
        """
        if self._client is None:
            return
        user = (user_content or "").strip()
        assistant = (assistant_content or "").strip()[:_CAPTURE_TURN_MAX_CHARS]
        text = f"{user}\n{assistant}".strip()
        if not text:
            return
        sid = session_id or "default"
        flush_now = False
        with self._capture_lock:
            prev = self._capture_buffers.get(sid, "")
            combined = f"{prev}\n{text}" if prev else text
            # Keep the newest tail (mirror CAPTURE_TAIL_KEEP).
            if len(combined) > _CAPTURE_MAX_CHARS:
                combined = combined[-_CAPTURE_MAX_CHARS:]
            self._capture_buffers[sid] = combined
            try:
                threshold = int(self._config.get("captureFlushChars") or _CAPTURE_FLUSH_CHARS)
            except (TypeError, ValueError):
                threshold = _CAPTURE_FLUSH_CHARS
            flush_now = len(combined) >= threshold
        if flush_now:
            self._flush_capture(sid, synchronous=False)

    def _flush_capture(self, session_id: str, *, synchronous: bool) -> None:
        """Send the session's buffered text to /capture. On failure the buffer
        is retained for the next flush (mirror CAPTURE_BUFFER_AFTER_WRITES)."""
        with self._capture_lock:
            if session_id in self._capture_flushing:
                return
            text = self._capture_buffers.get(session_id, "")
            if not text:
                return
            self._capture_buffers.pop(session_id, None)
            self._capture_flushing.add(session_id)

        def _run():
            try:
                self._client.capture({"sessionID": session_id, "text": text})
            except Exception as e:
                logger.debug("Lorekeeper capture flush failed: %s", e)
                # Retain for next flush.
                with self._capture_lock:
                    prev = self._capture_buffers.get(session_id, "")
                    self._capture_buffers[session_id] = f"{prev}\n{text}" if prev else text
            finally:
                with self._capture_lock:
                    self._capture_flushing.discard(session_id)

        if synchronous:
            _run()
        else:
            self._executor.submit(_run)

    def on_session_end(self, messages: List[Dict[str, Any]]) -> None:
        """Flush any buffered capture at a real session boundary."""
        self._flush_capture(self._current_session, synchronous=False)

    def on_session_switch(
        self, new_session_id: str, *, parent_session_id: str = "", reset: bool = False, rewound: bool = False, **kwargs,
    ) -> None:
        """Flush capture buffers on a genuinely new conversation so nothing
        buffered is lost. Flushes every buffered session, not just
        _current_session: sync_turn keys buffers by the session_id it was
        given, which can diverge from _current_session (subagent turns,
        rewinds) — flushing only the tracked one would strand those buffers.
        """
        if reset:
            with self._capture_lock:
                sids = [s for s in self._capture_buffers if s != new_session_id]
            for sid in sids:
                self._flush_capture(sid, synchronous=False)
        self._current_session = new_session_id

    def on_pre_compress(self, messages: List[Dict[str, Any]]) -> str:
        """Flush before compression so the compressed-away content is captured."""
        if self._current_session:
            self._flush_capture(self._current_session, synchronous=False)
        return ""

    # -- tools ---------------------------------------------------------------

    def _ensure_client(self) -> None:
        """Resolve the shared client (lorekeeper.json/token) without session kwargs.

        MemoryManager.add_provider() calls get_tool_schemas() BEFORE
        initialize() has run (initialize is what normally builds the
        client), so get_tool_schemas() must be able to resolve it lazily —
        otherwise the provider registers 0 tools, the dispatch routing
        table stays empty, and every lorekeeper_* call falls through to
        the registry as "Unknown tool". Uses the same sig-cached singleton
        as the plugin toolset (no duplicate config reads or connections).
        """
        if self._client is not None:
            return
        self._client = get_client()

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        """Fetch the full tool surface from the service (34 fork tools).

        Routed through the shared schema cache so the plugin toolset's
        registration reuses the same fetch instead of a second /tools call.
        """
        if self._client is None:
            self._ensure_client()
        if self._client is None:
            return []
        return get_tool_schemas(self._client)

    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs) -> str:
        """Generic dispatch: every lorekeeper_* tool runs on the service."""
        if self._client is None:
            return json.dumps({"error": "Lorekeeper service not initialized. Is the service running? (see Lorekeeper README)"})
        try:
            result = self._client.tool(tool_name, args)
            err = error_from_result(result)
            if err is not None:
                return tool_error(f"Lorekeeper tool failed: {err}")
            # The service returns {result: <string|object|array>}.
            payload = result.get("result")
            if isinstance(payload, str):
                return payload
            return json.dumps(payload)
        except LorekeeperError as e:
            return tool_error(f"Lorekeeper tool failed: {e}")
        except Exception as e:
            return tool_error(f"Lorekeeper tool failed: {e}")


def register(ctx) -> None:
    """Register Lorekeeper as a memory provider plugin + plugin toolset."""
    ctx.register_memory_provider(LorekeeperMemoryProvider())
    # Also register the toolset path: on some builds (notably the api_server
    # platform on vgit.99721dc) memory-provider tool injection never reaches
    # the model payload. Plugin toolsets flow through the normal registry on
    # every platform, and the provider's own injection skips already-present
    # names, so registering both paths is duplicate-safe everywhere.
    with suppress(Exception):
        from .tools import register_tools
        register_tools(ctx)